name: Pull and Save Docker Image windows-arm

on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称 多个用英文逗号分开'
        required: true
        default: 'dockcross/base:latest'  # 设置默认的 Docker 镜像列表
      suffix:
        description: '请填写压缩包名称'
        required: true
        default: 'image'

jobs:
  pull_and_package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Pull Docker Images and Package
      run: |
        images="${{ github.event.inputs.docker_images }}"
        IFS=',' read -r -a image_array <<< "$images"
        for image in "${image_array[@]}"; do
          docker pull "${image}"
          docker save "${image}" -o "${image//\//_}-${suffix}.tar"
        done
    - name: Compress the TAR files
      run: tar -czf ${suffix}.tar.gz *-${suffix}.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-${suffix}-tar
        path: ${suffix}-images.tar.gz
        retention-days: 30  # 将保留天数设置为 1 天 最多可设置90天

    - name: Clean up intermediate files
      run: |
        rm *-${suffix}.tar
