name: Pull and Save Docker Image windows-arm

on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称 多个用英文逗号分开'
        required: true
        default: 'dockcross/windows-armv7:latest,dockcross/windows-arm64:latest'  # 设置默认的 Docker 镜像列表

jobs:
  pull_and_package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Pull Docker Images and Package
      run: |
        images="${{ github.event.inputs.docker_images }}"
        IFS=',' read -r -a image_array <<< "$images"
        for image in "${image_array[@]}"; do
          docker pull "${image}"
          docker save "${image}" -o "${image//\//_}-cross-windows-arm.tar"
        done
    - name: Compress the TAR files
      run: tar -czf cross-windows-arm-images.tar.gz *-cross-windows-arm.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-cross-windows-arm-images-tar
        path: cross-windows-arm-images.tar.gz
        retention-days: 30  # 将保留天数设置为 1 天 最多可设置90天

    - name: Clean up intermediate files
      run: |
        rm *-cross-windows-arm.tar
